# Generated by Django 2.2.2 on 2019-06-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heart',
            name='chest_pain_type',
            field=models.PositiveIntegerField(choices=[(0, 'Type 0'), (1, 'Type 1'), (2, 'Type 2'), (3, 'Type 3')]),
        ),
        migrations.AlterField(
            model_name='heart',
            name='exercise_induced',
            field=models.PositiveIntegerField(choices=[(1, 'YES'), (0, 'NO')]),
        ),
        migrations.AlterField(
            model_name='heart',
            name='is_fasting_blood_sugar_greater_than_120_mg_dl',
            field=models.PositiveIntegerField(choices=[(1, 'Greater than 120 mg/dl'), (0, 'Less than 120 mg/dl')]),
        ),
        migrations.AlterField(
            model_name='heart',
            name='resting_electrocardiograph',
            field=models.PositiveIntegerField(choices=[(0, 'Type 0'), (1, 'Type 1'), (2, 'Type 2')]),
        ),
        migrations.AlterField(
            model_name='heart',
            name='sex',
            field=models.PositiveIntegerField(choices=[(1, 'male'), (0, 'female')]),
        ),
        migrations.AlterField(
            model_name='heart',
            name='slope_Type',
            field=models.PositiveIntegerField(choices=[(0, 'Type 0'), (1, 'Type 1'), (2, 'Type 2')]),
        ),
        migrations.AlterField(
            model_name='heart',
            name='target',
            field=models.PositiveIntegerField(choices=[(1, 'Yes'), (0, 'No')]),
        ),
        migrations.AlterField(
            model_name='heart',
            name='thal',
            field=models.PositiveIntegerField(choices=[(3, 'Normal'), (6, 'Fixed Defect'), (7, 'Reversable Defect')]),
        ),
    ]
